apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-nodejs-k8s
  labels:
    app: simple-nodejs-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-nodejs-k8s
  template:
    metadata:
      labels:
        app: simple-nodejs-k8s
    spec:
      containers:
        - name: simple-nodejs-k8s
          image: dinaldocker/simple-nodejs-k8s:latest
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
